---
# tasks file for waal70.vaultwarden
- name: "Template the vaultwarden.yml file to the role's files/ directory"
  ansible.builtin.template:
    src: vaultwarden.yml.j2
    dest: "{{ role_path }}/files/vaultwarden.yml"
    owner: "{{ interactive_user }}"
    group: "{{ interactive_user }}"
    mode: '0644'
    force: true
  delegate_to: localhost

- name: "Include role to deploy paperless-ngx-stack to Portainer"
  ansible.builtin.include_role:
    name: waal70.portainer
  vars:
    stack_list:
      - name: vaultwarden
        file: vaultwarden.yml # file is in files/ of this role

- name: "Return the vaultwarden yaml back to its placeholder version"
  ansible.builtin.copy:
    src: vaultwarden.yml.placeholder
    dest: "{{ role_path }}/files/vaultwarden.yml"
    owner: "{{ interactive_user }}"
    group: "{{ interactive_user }}"
    mode: '0644'
    remote_src: false
    force: true
  delegate_to: localhost
